DROP TABLE IF EXISTS VIEWED_EPISODES;
DROP TABLE IF EXISTS VIEWED_MOVIES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS MOVIES;
DROP TABLE IF EXISTS EPISODES;
DROP TABLE IF EXISTS SERIES;

CREATE TABLE IF NOT EXISTS USERS (
  ID SERIAL,
  NAME VARCHAR(20)
);
